---
title: "Analytical Results"
author: "Mwessel"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Analytical Results Page - All products are DRAFT


### Measures of Association
tests of association between total braun blanquet scores and time for the period of 2011 and 2020.
these tests were done in an attempt to identify an objective measure of "stable" transects over recent time.

The mantel Haenszel test was used to test for nonzero correlation and row mean differences
[Mantel Haenszel chisquare](https://mikewessel.github.io/AP/docs/Chisq.pdf){target="_blank"} 

while the [Cochrane Armitage trend test](https://mikewessel.github.io/AP/docs/Cochrane.pdf){target="_blank"} 
relied on iterative tests using binomial assignment of BB scores (e.g. BB score<=1 versus > 1) for scores 1 through 5. If results of all comparisons were non-significant the station was considered stable over time. 

### [Total BB Boxplots](https://mikewessel.github.io/AP/docs/totalBB.pdf){target="_blank"}
These plots include boxplots of total braun blanquet score distributions by strata followed by panel plots of 
individual transect total BB scores within each strata

### [Flow Anomalies](https://mikewessel.github.io/AP/docs/doit.pdf){target="_blank"}
Flow records for USGS gages within the study area were downloaded for the entire period of record, subset to 1998 through 2020
and standardized to create an index of flow representing drought or surplus conditions. The standardization procedure included:
Natural log transformation of the raw flow timeseries (a constant of 0.01 was added to adjust for values of zero),
calculation of the mean and standard deviation of the natural log transformed values by month to obtain long term monthly averages   and mapping deviation of each date in the timeseries to the long term monthly average. 

That is:
    (date flow - monthly mean flow)/std(monthly mean flow)
    
This function produces a timeseries of daily values expressed in term of deviations from long term averages in units of standard deviation such that the mean is zero. Deviations greater than +/- 2 indicate strong deviations from long term average conditions.

The 1st and 99th percentile of the standardized values were then identified as "anomalies" to identify "events" that may have affected water quality and seagrass in the estuary. Hurricane Irma for example is one such event. 










