---
title: "Index"
author: "Mwessel"
date: "7/19/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r global-options, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)
```


## Background

Collaborative Site For Aquatic Preserve Water Quality and Seagrass Assessment
All materials are draft and not to be used for public dissemination


```{r setup}

library(tidyverse)
library(sf)
library(haven)
library(plotly)
library(leaflet)
library(here)
```

# Interactive Map 
Display of aquatic preserve seagrass transect locations and associated FDEP Waterbody Identifiers (WBIDs)


```{r package-options, include=TRUE}
knitr::opts_knit$set(message=FALSE,echo=FALSE)

setwd(here::here("./shapes"))

#IWR_wbid <- sf::read_sf(dsn = ".", layer = "WBID_Run61")%>%
#    filter(WBID %in% c("1983A1","1983A","1983B","1991B","2065A","2065B","2065C","2065D","2065E","2065F","2065G","2065H1","1991A","2056A","2056B","3240A","3240B","3258A1","3258I"))

#st_write(st_as_sf(IWR_wbid),"IWR_wbid.shp")

IWR_wbid<-st_read("IWR_wbid.shp")

CHAP_tr <- sf::read_sf(dsn = ".", layer = "CHAP_SG_Stat21_Proj")
EBAP_tr <- sf::read_sf(dsn = ".", layer = "EBAP_SG_Stat21_Proj")


# assign crs
IWR_wbid <- st_transform(IWR_wbid, crs = 4326)
CHAP_tr <- st_transform(CHAP_tr , crs = 4326)
EBAP_tr <- st_transform(EBAP_tr, crs = 4326)

# plot
leaflet::leaflet() %>%
  leaflet::addProviderTiles(providers$CartoDB.Voyager) %>%
  leaflet::addPolygons(color = "#222", weight = 2, opacity = 1, fillOpacity = 0,label = ~lapply(WBID, htmltools::htmlEscape), data = IWR_wbid ) %>%
  leaflet::addCircles(color = "green", label = ~lapply(Site, htmltools::htmlEscape),data = CHAP_tr)%>%
  leaflet::addCircles(color = "blue", label = ~lapply(Site, htmltools::htmlEscape),data = EBAP_tr)
```



